WIP: Add loading animation for loading results
sandboxnu/searchneu-old pull request #145
Opened 2020-03-19 18:02 UTC by NEUDitao

This is. a really rough WIP mockup right now, but DJ and I were talking last night about adding some sort of indication that a search is happening/results are being fetched. (This also moves EmptyResultsContainer to its own file to make readability slightly better in Results)

*current issues:*

- The SVG is still "boxed in," some good old OOD debugging would probably get that out of the way
- It seems that the animation has to complete before searches are loaded. A quick and easy fix would be to make the animation really short, but that's not a solution, just a way to mask over it. Another way would probably be to figure out how to escape the animation early when isReady in Results.tsx is done

2020-03-19 18:10 UTC, ryanhugh commented
Lets chat over messenger - but I think we shouldn't even need a loading animation if 90% of the searches take < 100 ms :)

2020-03-19 19:49 UTC, dajinchu commented
maybe we show blank white, but put the magnifying glass when the search takes longer than some threshold. would be good for people on slow connections

2020-03-20 02:36 UTC, dajinchu commented
going to cherry pick the first commit into filter-state as it will be hard to merge later. this PR should remain for the animation stuff

2020-03-21 02:05 UTC, gamburgm commented on frontend/components/pages/Results.tsx
> +          {!isReady && <LoadingContainer />}
I feel like it would be a little better if this were more explicit rather than leveraging the `&&` evaluation, but I am no expert on React style

2020-03-21 02:08 UTC, gamburgm commented
Could you post a screenshot? Unless @dajinchu has already looked at it and approves.

2020-03-21 02:41 UTC, dajinchu requested changes

2020-03-21 02:41 UTC, dajinchu commented on frontend/components/pages/LoadingContainer.tsx
> +  const [showBlank, setDoAnimation] = useState(true);
hook convention for useState is `[X, setX]`

2020-03-21 02:41 UTC, dajinchu commented on frontend/components/images/moving_logo.html
> +
delete this and moving_logo.css

2020-03-21 02:41 UTC, dajinchu commented on frontend/components/pages/LoadingContainer.tsx
> +  });
timeout needs to be cleaned up or it trigger after the container has been unmounted.
https://upmostly.com/tutorials/settimeout-in-react-components-using-hooks

2020-03-21 02:41 UTC, dajinchu commented on frontend/components/pages/EmptyResultsContainer.tsx
> +interface EmptyResultsProps {
EmptyResultsContainer and LoadingContainer should be moved to the `ResultsPage` folder

2020-03-21 02:41 UTC, dajinchu commented on frontend/css/pages/_LoadingContainer.scss
> +  stroke-dashoffset: 0;
put this in the top level of the css folder, not inside /pages. we need to figure out better css organization, but for now let's just keep current the convention.

2020-03-21 02:42 UTC, dajinchu commented on frontend/components/pages/Results.tsx
> +          {!isReady && <LoadingContainer />}
this is pretty typical React, though people are divided on whether its good style. I don't think it matters much

2020-03-21 04:18 UTC, NEUDitao commented
> Could you post a screenshot? Unless @dajinchu has already looked at it and approves.

Not perfect, but https://drive.google.com/file/d/1ECrSULYWEVnJOMIv_GJLDuueehFwMPfc/view?usp=sharing

Any size adjustments/style adjustments welcome!

2020-03-22 05:46 UTC, dajinchu commented
coolio. if you can fix jest we can merge

2020-03-23 00:42 UTC, merged