Add a range filter for courseID.
sandboxnu/searchneu-old pull request #156
Opened 2020-03-29 01:51 UTC by zefwang

2020-03-29 02:27 UTC, dajinchu reviewed
we need a pill still right?

2020-03-29 02:27 UTC, dajinchu commented on frontend/css/_Filters.scss
> +.input-box {
for these 3 css rules they could all be inside 1 BEM block, so we could have `range-filter` with `range-filter__input` `range-filter__min` etc inside. see how other rules take advantage of scss using `&__`

2020-03-29 02:27 UTC, dajinchu commented on frontend/css/_Filters.scss
> +.input-box {
https://css-tricks.com/using-sass-control-scope-bem-naming/

2020-03-29 03:31 UTC, NEUDitao approved these changes

2020-03-30 03:39 UTC, NEUDitao approved these changes

2020-04-01 00:38 UTC, dajinchu requested changes

2020-04-01 00:38 UTC, dajinchu commented on frontend/components/ResultsPage/filters.ts
> +type ClassRange = {min:number, max:number} | {};
export this type so we can use it in the RangeFilter

2020-04-01 00:38 UTC, dajinchu commented on frontend/components/ResultsPage/RangeFilter.tsx
> +  selected: {min:string, max:string},
Import and use the ClassRange type from `filters.ts`

2020-04-01 00:38 UTC, dajinchu commented on frontend/components/ResultsPage/RangeFilter.tsx
> +            onChange={ (event) => setControlledInput({ min:event.target.value, max: (controlledInput.max ? controlledInput.max : null) }) }
should the default max be null? or 9999? I'm not exactly sure but this might trigger some error if you only set the min and then hit apply. Not sure - you should test this

2020-04-01 00:38 UTC, dajinchu commented on frontend/components/ResultsPage/RangeFilter.tsx
> +  const [controlledInput, setControlledInput] = useState(selected);
this structure is good

2020-04-01 22:15 UTC, dajinchu requested changes

2020-04-01 22:15 UTC, dajinchu commented on frontend/components/ResultsPage/RangeFilter.tsx
> +            onChange={ (event) => setControlledInput({ min:event.target.value, max: (controlledInput.max ? controlledInput.max : null) }) }
easier to write 
`X ? X : Y` as `X || Y`

all the ternaries in this can be written this way

2020-04-02 00:32 UTC, dajinchu commented on frontend/components/ResultsPage/FilterPills.tsx
> +        verbose: spec.display,
we need the min/max values in the pill so it says like "Course Number: 2000 - 5000" instead of just "Course Number" 

You can use string templating for this (see the Options pills for an example)

2020-04-02 00:34 UTC, dajinchu requested changes

2020-04-02 00:34 UTC, dajinchu commented on frontend/components/ResultsPage/filters.ts
> +  category: FilterCategories.Range, default: {}, display: 'Course ID Range', order: 5,
Let's change the display to "Course Number" I think the min/max input makes it obviously a range

2020-04-04 00:52 UTC, dajinchu commented on frontend/components/ResultsPage/RangeFilter.tsx
> +            type='string'
set type number

2020-04-04 00:54 UTC, dajinchu commented on frontend/components/ResultsPage/filters.ts
> +export type ClassRange = {min:string, max:string} | { min:'', max:'' };
make this `{min:number|null, max:number|null}` Class Ids are a numeric range. It's kinda weird to store them as strings

2020-04-04 00:55 UTC, dajinchu commented on frontend/components/ResultsPage/RangeFilter.tsx
> +            value={ controlledInput.min || '' }
once you change the ClassRange so `.min` is number|null, you won't need the `||` thing at all

2020-04-04 00:55 UTC, dajinchu commented on frontend/components/ResultsPage/RangeFilter.tsx
> +            onChange={ (event) => setControlledInput({ min:event.target.value, max: (controlledInput.max || null) }) }
You'll have to use parseInt here on `event.target.value` and you can get rid of the `||` for max

2020-04-04 00:56 UTC, dajinchu commented on frontend/components/ResultsPage/RangeFilter.tsx
> +          <label className='RangeFilter__label-max'>To: </label>
I think the new Figma design doesn't have `From:` or `To:` anymore? It just puts "min" and "max into the input placeholder

2020-04-04 00:56 UTC, dajinchu commented on frontend/css/_Filters.scss
> +  &__input-box {
Is it possible the input box to look more like the design?

2020-04-06 19:25 UTC, dajinchu approved these changes

2020-04-06 19:25 UTC, merged