Updater a new hope
sandboxnu/searchneu-old pull request #163
Opened 2020-04-07 21:02 UTC by gamburgm

WIP

2020-04-08 21:18 UTC, dajinchu commented on backend/tests/updater.test.ts
> +      await FollowedSection.create({
can't you generalize most of these fixtures Prelude-style? I can already hear Matthias roasting us

2020-04-08 21:46 UTC, dajinchu requested changes
this is some 🥚cellent code

2020-04-08 21:46 UTC, dajinchu commented on backend/tests/updater.test.ts
> +      await Section.create({
maybe you can generalize this by adding a function `createEmptySection` that takes the SectionType object sort of like a tempalte, zeros out the seats + adds id/classHash, and `Section.create` it.

2020-04-08 21:46 UTC, dajinchu commented on backend/tests/updater.test.ts
> +      expect(notifyer.sendFBNotification.mock.calls).toEqual([
These tests SLAP

2020-04-08 21:46 UTC, dajinchu commented on backend/updater.ts
> +    return new this();
wack. i know this is the old interface, but maybe let's just change it? Is there any good reason not to just call the constructor?

2020-04-08 21:46 UTC, dajinchu commented on backend/updater.ts
> +    this.update();
should we await this?

2020-04-08 21:46 UTC, dajinchu commented on backend/updater.ts
> +      if (!acc[hash]) acc[hash] = [];
since we're mutating acc anyway, there's no point in writing a reduce here. this could just be a `for...of` or `forEach`

2020-04-08 21:46 UTC, dajinchu commented on backend/updater.ts
> +export type Notification = CourseNotification | SectionNotification;
this is so good

2020-04-08 21:46 UTC, dajinchu commented on backend/updater.ts
> +  async modelToUserHash(modelName: string): Promise<Record<string, string[]>> {
this is a scary abstraction. maybe make `modelName: 'course' | 'section`

2020-04-09 00:28 UTC, gamburgm commented on backend/updater.ts
> +  async modelToUserHash(modelName: string): Promise<Record<string, string[]>> {
that is a VERY good call

2020-04-09 00:29 UTC, gamburgm commented on backend/updater.ts
> +    this.update();
There's no reason for the call to be synchronous, we can just let it go.

2020-04-09 00:30 UTC, gamburgm commented on backend/updater.ts
> +    return new this();
It's nice to just call `Updater.create().start()` rather than having to do `(new Updater()).start()`, but that's the only difference.

2020-04-09 00:30 UTC, gamburgm commented on backend/tests/updater.test.ts
> +      await FollowedSection.create({
:egg:

2020-04-09 01:31 UTC, dajinchu commented on backend/updater.ts
> +    return new this();
I see. it'd probably be even better to just export a `startUpdater()` function from this module. but it really does not matter at all

2020-04-10 04:27 UTC, merged