Suggests to remove filters if there are no results + filters applied
sandboxnu/searchneu-old pull request #172
Opened 2020-04-19 04:47 UTC by beccajohnson17

Will still suggest searching on Google _if no filters are applied_

2020-04-19 18:01 UTC, dajinchu commented on frontend/components/ResultsPage/EmptyResultsContainer.tsx
> +        { noResultsHeader }
putting in bits of jsx in like this makes it a bit harder to understand what's going on quickly. Generally I think it's better to leave all the jsx together in one chunk when possible. Obviously the return inside and outside the if statement are very similar. Instead of having two return statements, imo it would be better to do a [inline if/ternary operator](https://reactjs.org/docs/conditional-rendering.html#inline-if-else-with-conditional-operator)
eg:
```
return (
<div>
  <h3> no results <h3/>
  <div className='empty bottom line'>
  { filtersApplied ? (
    Try <div role='button'...> clearing </div> filters...
  ) : (
    want to search goggle?
  )}
  </div>>
</div>
)
```

2020-04-19 18:06 UTC, dajinchu commented on frontend/components/pages/Results.tsx
> +  const filtersApplied: Boolean = areFiltersSet(filters);
the name `filtersApplied` used here and in the EmptyResultsContainer might be interpreted as containing "which filters are applied" not "are there applied filters?" I might just name it `filtersAreSet` or even just `areFiltersSet` (this causes a name conflict between areFiltersSet the constant and areFiltersSet the function. You can resolve it by changing line 26 of this file to import `areFiltersSet as getFiltersSet` which aliases the import)

2020-04-19 18:07 UTC, dajinchu requested changes

2020-04-19 18:07 UTC, dajinchu commented on frontend/css/_FilterPills.scss
> +div [class$="__clear"] {
what other classes end in __clear? global rules can be a bit risky

2020-04-20 02:18 UTC, beccajohnson17 commented on frontend/css/_FilterPills.scss
> +div [class$="__clear"] {
currently, nothing. But this was a concern I had too.

2020-04-20 04:09 UTC, beccajohnson17 commented on frontend/components/ResultsPage/EmptyResultsContainer.tsx
> +        { noResultsHeader }
I'm having a lot of trouble with this. I'm not sure where I'm going wrong but it always says "Cannot find name 'Try'" for the html.

2020-04-20 04:17 UTC, beccajohnson17 commented on frontend/components/ResultsPage/EmptyResultsContainer.tsx
> +        { noResultsHeader }
lol nvm im dumb

2020-04-20 19:25 UTC, dajinchu commented on frontend/css/_FilterPills.scss
> +div [class$="__clear"] {
then I think you could just write these css rules using
```
.no-result__clear {
...
}
```

2020-04-21 00:30 UTC, beccajohnson17 commented on frontend/css/_FilterPills.scss
> +div [class$="__clear"] {
So the reason I did that is that it shares a lot of the same code as the clear all filters button, with the exception of the padding. I couldn't think of another way to write it for both of them without duplicate code. I could do it separately for each, though.

2020-04-21 18:07 UTC, dajinchu commented on frontend/css/_FilterPills.scss
> +div [class$="__clear"] {
I think just write them separately. overlapping css rules are more dangerous than duplicate css rules generally.

2020-04-21 21:21 UTC, beccajohnson17 commented on frontend/css/_FilterPills.scss
> +div [class$="__clear"] {
Ok thanks!

2020-04-23 13:43 UTC, NEUDitao approved these changes

2020-05-01 23:54 UTC, dajinchu approved these changes
awesome

2020-05-02 03:09 UTC, merged