Feedback rework
sandboxnu/searchneu-old pull request #177
Opened 2020-05-03 22:33 UTC by amielmon

Move functionality of feedback header into feedback modal

2020-05-09 03:35 UTC, NEUDitao requested changes

2020-05-09 03:35 UTC, NEUDitao commented on frontend/components/ResultsPage/FeedbackModal/FeedbackModalInitial.tsx
> +export default function FeedbackModalInitial({ setYes } : InitialStepProps) {
something something purpose statement something something design recipe

2020-05-09 03:35 UTC, NEUDitao commented on frontend/components/ResultsPage/FeedbackModal/FeedbackModal.tsx
> +    switch (step) {
can we make the step initial|checkbox|free an enum?

2020-05-09 03:35 UTC, NEUDitao commented on frontend/components/ResultsPage/FeedbackModal/FeedbackModalFree.tsx
> +        <textarea
not too familiar  with textareas and really tired, but do we need to encode their feedback in some way to make sure we don't get haxored?

2020-05-09 18:10 UTC, amielmon commented on frontend/components/ResultsPage/FeedbackModal/FeedbackModalFree.tsx
> +        <textarea
pretty sure react is safe from xss, so this shouldn't be a concern

2020-05-09 18:56 UTC, ryandrew14 reviewed
Nice hooks

2020-05-09 18:56 UTC, ryandrew14 commented on frontend/components/ResultsPage/FeedbackModal/FeedbackModal.tsx
> +  const [step, setStep] = useState('initial');
Maybe you want to use `useReducer` here?

2020-05-09 18:56 UTC, ryandrew14 commented on frontend/components/ResultsPage/useClickOutside.ts
> +export default function useClickOutside(ref: React.RefObject<HTMLElement>, flag: boolean, setFlag: (b: boolean) => void) {
This is hot

2020-05-09 22:48 UTC, amielmon commented on frontend/components/ResultsPage/FeedbackModal/FeedbackModal.tsx
> +  const [step, setStep] = useState('initial');
Hmm, I have a lot of state but they're all independent of each other (changing the state of one has no effect on the other pieces of state). Not sure if I need to group all of them into a reducer. What were your thoughts?

2020-05-21 21:08 UTC, NEUDitao approved these changes

2020-05-21 21:17 UTC, merged