primsa
sandboxnu/searchneu-old pull request #195
Opened 2020-09-16 13:34 UTC by gamburgm

WIP

2020-09-17 05:53 UTC, dajinchu requested changes
First look. Need to run locally but not tonight

2020-09-17 05:53 UTC, dajinchu commented on backend/graphql/resolvers/class.ts
> +  await prisma.$disconnect();
this seems like a bad idea. we're going to be opening and closing so many connections when big graphql queries come in. Remember that resolvers can get called an unbounded number of times in a single graphql request

2020-09-17 05:53 UTC, dajinchu commented on backend/searcher.ts
> +      this.subjects = new Set((await this.prisma.$queryRaw('SELECT DISTINCT subject FROM courses;')).map((res) => res.subject));
Why not use the Prisma Distinct features? https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/distinct

2020-09-17 05:53 UTC, dajinchu commented on create_tables.sql
> +CREATE TABLE courses (
do we still need this if we also have the prisma migrations?

2020-09-17 05:53 UTC, dajinchu commented on package.json
>    "dependencies": {
remember to uninstall sequelize stuff

2020-09-17 05:53 UTC, dajinchu commented on package.json
>      "test:migrate": "npx sequelize-cli --env test db:migrate",
Probably wanna convert dev:migrate etc to use prisma stuff instead?

2020-09-17 05:58 UTC, gamburgm commented on backend/graphql/resolvers/class.ts
> +  await prisma.$disconnect();
Yeah I think you're right, I did this b/c prisma connections don't terminate at the ends of tests, so tests hang if each connection isn't manually disconnected. Can find a different work around for this tho

2020-09-18 16:12 UTC, gamburgm commented on backend/graphql/resolvers/class.ts
> +  await prisma.$disconnect();
Does Apollo allow for post-request cleanup? `Context` is useful here for setting up a connection-per-request, but I'd still like to shut down open connections so that tests and other scripts that use the resolvers don't hang.

2020-09-19 19:16 UTC, merged