Improve Dropdown Functionality
sandboxnu/searchneu-old pull request #198
Opened 2020-10-04 20:31 UTC by puneetjohal

Improved dropdown functionality by adding the following features:

- The dropdown stays expanded when a user selects a filter or clicks on the search box to manually search for a filter
- The dropdown stays expanded as users are deselecting filters
- The search box clears the text after the user selects a filter from the dropdown to prepare for a new search
- The dropdown displays a message saying "No results found." if the search does not match any applicable filters, or if there are no more filters to choose from
- The arrow/triangle on the right points in different directions depending on whether the dropdown is expanded or not, also added a simple animation to go along with this
- The dropdown will appear disabled if there are no pre-selected filters and there are no filters available to choose from (visually, the dropdown will be grayed out, no special cursors will appear when hovering over different sections of the dropdown, the placeholder text will read "No filters apply", and the dropdown will be unable to expand)

2020-11-04 05:36 UTC, gamburgm requested changes
One small change, and then I think we're good to ship!

2020-11-04 05:36 UTC, gamburgm commented on frontend/css/_DropdownFilter.scss
> +  &__noResults {
can you rename this to `&--noResults`? Take a look at the [BEM spec](http://getbem.com/naming/), will hopefully clarify what I mean here.

2020-11-04 17:26 UTC, NEUDitao approved these changes

2020-11-04 19:30 UTC, puneetjohal commented on frontend/css/_DropdownFilter.scss
> +  &__noResults {
Done (in both the stylesheet and DropdownFilter.tsx)

2020-11-06 03:04 UTC, gamburgm approved these changes
Yeet!

2020-11-06 03:04 UTC, merged