Some cleanup on Home.js
sandboxnu/searchneu-old pull request #76
Opened 2019-11-04 00:45 UTC by amielmon

-Arrowify event listener functions and remove binds
-URL properly changes when clicking on logo
-Replace open/close for feedback and help forms with single toggle

2019-11-07 01:08 UTC, gamburgm commented
Looking good to me! Going to get @dajinchu to take a closer look since I'm less experienced with the stuff, but glad we get to get this code in.

2019-11-07 01:44 UTC, dajinchu commented
Looks good. Could you update the snapshots? Tests are failing.

2019-11-07 16:21 UTC, ryanhugh commented
> -Arrowify event listener functions and remove binds

People have asked me about this before and I originally didn't support moving over because sublime text didn't use to recognize functions with this new syntax as methods (so shortcuts like ctrl-r didn't work) but looks like sublime now supports them! Woo!!

You could probably make these changes throughout the rest of the codebase too, if ya wanted :)

Great work!!

2019-11-19 12:33 UTC, dajinchu requested changes

2019-11-19 12:33 UTC, dajinchu commented on backend/graphql/tests/__snapshots__/index.test.js.snap
>  exports[`gets all occurrences 1`] = `
can you undo the changes to this snapshot

2019-11-25 05:40 UTC, dajinchu approved these changes
👍

2019-11-26 03:47 UTC, merged