Insert Scraped Data into Postgres
sandboxnu/searchneu-old pull request #84
Opened 2019-11-23 15:28 UTC by gamburgm

WIP

2019-12-04 02:34 UTC, gamburgm commented on backend/dumpProcessor.js
> +class dumpProcessor {
Not sure if specs are necessary here—we could spec that the data is getting processed in the process functions and then that `bulkCreate` does what we expect it to, but neither of those things seem worth spec-ing out.

2019-12-09 04:22 UTC, dajinchu requested changes
i see we deleted meetings. do we need a migration to drop the meetings table then?

2019-12-09 04:22 UTC, dajinchu commented on backend/dumpProcessor.js
> +  chunkify(arr) {
https://lodash.com/docs/4.17.15#chunk

2019-12-09 04:22 UTC, dajinchu commented on backend/tests/dumpProcessor.test.js
> +    const prevCounts = await getCounts();
are we unable to just clean out the whole table before each tests?

2019-12-09 12:14 UTC, gamburgm commented on backend/dumpProcessor.js
> +  chunkify(arr) {
Nice

2019-12-09 12:14 UTC, gamburgm commented on backend/tests/dumpProcessor.test.js
> +    const prevCounts = await getCounts();
I was already doing that, not sure what I was thinking

2019-12-09 12:15 UTC, gamburgm reviewed
> i see we deleted meetings. do we need a migration to drop the meetings table then?

I was honestly thinking of just dropping the database and re-building it on these migrations, I didn't want to pollute our migrations with the changes we made as we figure out the best way to configure our data early on.

2019-12-11 02:36 UTC, dajinchu approved these changes
👍

2019-12-11 04:14 UTC, merged